### ISSUE TITLE
Installation db_driver must be configured

### ISSUE THREAD

**Issue by electricBonfire** [robzienert/CalendarBundle#12]
I cloned your branch into /src/Rizza/CalendarBundle
Then added the bundle to the AppKernel as well as updating the config.yml and routing. I get the following error when going to /calendar

InvalidConfigurationException: The child node "db_driver" at path "rizza_calendar" must be configured.

**Comment by ravi-sam** [comment]
I've been investigating this bundle as well. I had to do the following to get past the above error:

```
# /app/config/config.yml

rizza_calendar:
   db_driver: orm
   class: 
      model: 
         calendar: [custom entity that extends Rizza\CalendarBundle\Entity\Calendar]
         event: [custom entity that extends Rizza\CalendarBundle\Entity\Event]
         user: [Custom user entity from the User Provider]
         attendee: [Custom entity that extends Rizza\CalendarBundle\Entity\Attendee]
```

I am still in the process of getting this bundle working for me.

**Comment by electricBonfire** [comment]
I have updated my config.yml:

```
rizza_calendar: 
    db_driver: orm
    class:
        model:
            calendar: Rizza\CalendarBundle\Entity\Calendar
            event: Rizza\CalendarBundle\Entity\Event
            user: Adaptive\UserBundle\Model\User
            attendee: Rizza\CalendarBundle\Entity\Attendee
```

Can I simply use the Entities provided with the bundle or do I need to extend them. Also my user class is an extension of the fosuserbundle.

I am now getting the following error:

[Semantical Error] line 0, col 61 near 'owner = :owner': Error: Class Rizza\CalendarBundle\Entity\Calendar has no field or association named owner
