### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by schingeldi** [robzienert/CalendarBundle#13]
I tried to install the bundle and got (hopefully) everything in place. But I can't call the url.

I always got:

InvalidTypeException: Invalid type for path "rizza_calendar.class.model.calendar". Expected scalar, but got array.

Any idea how this can happen?

I also tried to execute

php app/console doctrine:schema:update --force

to generate my database tables, but get the same error. 

Thanks for help

**Comment by dao** [comment]
your config should look something like this:

``` yml
rizza_calendar:
    db_driver: mongodb
    class:
        model:
            calendar: Application\Rizza\CalendarBundle\Document\Calendar
            event: Application\Rizza\CalendarBundle\Document\Event
            user: Application\Sonata\UserBundle\Document\User
            attendee: Application\Rizza\CalendarBundle\Document\Attendee
```

I also had to define a couple parameters:

``` yml
parameters:
    rizza_calendar.calendar_document.class: Application\Rizza\CalendarBundle\Document\Calendar
    rizza_calendar.event_document.class: Application\Rizza\CalendarBundle\Document\Event
```
