### ISSUE TITLE
Could not load type "rizza_calendar_calendar"

### ISSUE THREAD

**Issue by tworzenieweb** [robzienert/CalendarBundle#14]
I was trying to configure this bundle. I create bundle that extends this bundle.

```
rizza_calendar: 
    db_driver: orm

    class:
        model:
            calendar: Sylius\Sandbox\Bundle\CalendarBundle\Entity\Calendar
            event: Rizza\CalendarBundle\Entity\Event
            user: Adaptive\UserBundle\Model\User
            attendee: Rizza\CalendarBundle\Entity\Attendee
```

I have implemented classes that extend abstract models but i am still getting error Could not load type "rizza_calendar_calendar"

What else should I do to make this working correctly?
